// Code generated by ent, DO NOT EDIT.

package polloption

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"filip.filipovic/polling-app/model/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PollOption {
	return predicate.PollOption(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PollOption {
	return predicate.PollOption(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PollOption {
	return predicate.PollOption(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PollOption {
	return predicate.PollOption(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PollOption {
	return predicate.PollOption(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PollOption {
	return predicate.PollOption(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PollOption {
	return predicate.PollOption(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PollOption {
	return predicate.PollOption(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PollOption {
	return predicate.PollOption(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldEQ(FieldName, v))
}

// VoteCount applies equality check predicate on the "vote_count" field. It's identical to VoteCountEQ.
func VoteCount(v int) predicate.PollOption {
	return predicate.PollOption(sql.FieldEQ(FieldVoteCount, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.PollOption {
	return predicate.PollOption(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.PollOption {
	return predicate.PollOption(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldContainsFold(FieldName, v))
}

// VoteCountEQ applies the EQ predicate on the "vote_count" field.
func VoteCountEQ(v int) predicate.PollOption {
	return predicate.PollOption(sql.FieldEQ(FieldVoteCount, v))
}

// VoteCountNEQ applies the NEQ predicate on the "vote_count" field.
func VoteCountNEQ(v int) predicate.PollOption {
	return predicate.PollOption(sql.FieldNEQ(FieldVoteCount, v))
}

// VoteCountIn applies the In predicate on the "vote_count" field.
func VoteCountIn(vs ...int) predicate.PollOption {
	return predicate.PollOption(sql.FieldIn(FieldVoteCount, vs...))
}

// VoteCountNotIn applies the NotIn predicate on the "vote_count" field.
func VoteCountNotIn(vs ...int) predicate.PollOption {
	return predicate.PollOption(sql.FieldNotIn(FieldVoteCount, vs...))
}

// VoteCountGT applies the GT predicate on the "vote_count" field.
func VoteCountGT(v int) predicate.PollOption {
	return predicate.PollOption(sql.FieldGT(FieldVoteCount, v))
}

// VoteCountGTE applies the GTE predicate on the "vote_count" field.
func VoteCountGTE(v int) predicate.PollOption {
	return predicate.PollOption(sql.FieldGTE(FieldVoteCount, v))
}

// VoteCountLT applies the LT predicate on the "vote_count" field.
func VoteCountLT(v int) predicate.PollOption {
	return predicate.PollOption(sql.FieldLT(FieldVoteCount, v))
}

// VoteCountLTE applies the LTE predicate on the "vote_count" field.
func VoteCountLTE(v int) predicate.PollOption {
	return predicate.PollOption(sql.FieldLTE(FieldVoteCount, v))
}

// HasUsersVoted applies the HasEdge predicate on the "users_voted" edge.
func HasUsersVoted() predicate.PollOption {
	return predicate.PollOption(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, UsersVotedTable, UsersVotedPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsersVotedWith applies the HasEdge predicate on the "users_voted" edge with a given conditions (other predicates).
func HasUsersVotedWith(preds ...predicate.User) predicate.PollOption {
	return predicate.PollOption(func(s *sql.Selector) {
		step := newUsersVotedStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPoll applies the HasEdge predicate on the "poll" edge.
func HasPoll() predicate.PollOption {
	return predicate.PollOption(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PollTable, PollColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPollWith applies the HasEdge predicate on the "poll" edge with a given conditions (other predicates).
func HasPollWith(preds ...predicate.Poll) predicate.PollOption {
	return predicate.PollOption(func(s *sql.Selector) {
		step := newPollStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PollOption) predicate.PollOption {
	return predicate.PollOption(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PollOption) predicate.PollOption {
	return predicate.PollOption(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PollOption) predicate.PollOption {
	return predicate.PollOption(sql.NotPredicates(p))
}
