// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"filip.filipovic/polling-app/model/ent/poll"
	"filip.filipovic/polling-app/model/ent/polloption"
	"filip.filipovic/polling-app/model/ent/predicate"
	"filip.filipovic/polling-app/model/ent/user"
)

// PollOptionUpdate is the builder for updating PollOption entities.
type PollOptionUpdate struct {
	config
	hooks    []Hook
	mutation *PollOptionMutation
}

// Where appends a list predicates to the PollOptionUpdate builder.
func (pou *PollOptionUpdate) Where(ps ...predicate.PollOption) *PollOptionUpdate {
	pou.mutation.Where(ps...)
	return pou
}

// SetName sets the "name" field.
func (pou *PollOptionUpdate) SetName(s string) *PollOptionUpdate {
	pou.mutation.SetName(s)
	return pou
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pou *PollOptionUpdate) SetNillableName(s *string) *PollOptionUpdate {
	if s != nil {
		pou.SetName(*s)
	}
	return pou
}

// SetVoteCount sets the "vote_count" field.
func (pou *PollOptionUpdate) SetVoteCount(i int) *PollOptionUpdate {
	pou.mutation.ResetVoteCount()
	pou.mutation.SetVoteCount(i)
	return pou
}

// SetNillableVoteCount sets the "vote_count" field if the given value is not nil.
func (pou *PollOptionUpdate) SetNillableVoteCount(i *int) *PollOptionUpdate {
	if i != nil {
		pou.SetVoteCount(*i)
	}
	return pou
}

// AddVoteCount adds i to the "vote_count" field.
func (pou *PollOptionUpdate) AddVoteCount(i int) *PollOptionUpdate {
	pou.mutation.AddVoteCount(i)
	return pou
}

// AddUsersVotedIDs adds the "users_voted" edge to the User entity by IDs.
func (pou *PollOptionUpdate) AddUsersVotedIDs(ids ...int) *PollOptionUpdate {
	pou.mutation.AddUsersVotedIDs(ids...)
	return pou
}

// AddUsersVoted adds the "users_voted" edges to the User entity.
func (pou *PollOptionUpdate) AddUsersVoted(u ...*User) *PollOptionUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return pou.AddUsersVotedIDs(ids...)
}

// SetPollID sets the "poll" edge to the Poll entity by ID.
func (pou *PollOptionUpdate) SetPollID(id int) *PollOptionUpdate {
	pou.mutation.SetPollID(id)
	return pou
}

// SetNillablePollID sets the "poll" edge to the Poll entity by ID if the given value is not nil.
func (pou *PollOptionUpdate) SetNillablePollID(id *int) *PollOptionUpdate {
	if id != nil {
		pou = pou.SetPollID(*id)
	}
	return pou
}

// SetPoll sets the "poll" edge to the Poll entity.
func (pou *PollOptionUpdate) SetPoll(p *Poll) *PollOptionUpdate {
	return pou.SetPollID(p.ID)
}

// Mutation returns the PollOptionMutation object of the builder.
func (pou *PollOptionUpdate) Mutation() *PollOptionMutation {
	return pou.mutation
}

// ClearUsersVoted clears all "users_voted" edges to the User entity.
func (pou *PollOptionUpdate) ClearUsersVoted() *PollOptionUpdate {
	pou.mutation.ClearUsersVoted()
	return pou
}

// RemoveUsersVotedIDs removes the "users_voted" edge to User entities by IDs.
func (pou *PollOptionUpdate) RemoveUsersVotedIDs(ids ...int) *PollOptionUpdate {
	pou.mutation.RemoveUsersVotedIDs(ids...)
	return pou
}

// RemoveUsersVoted removes "users_voted" edges to User entities.
func (pou *PollOptionUpdate) RemoveUsersVoted(u ...*User) *PollOptionUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return pou.RemoveUsersVotedIDs(ids...)
}

// ClearPoll clears the "poll" edge to the Poll entity.
func (pou *PollOptionUpdate) ClearPoll() *PollOptionUpdate {
	pou.mutation.ClearPoll()
	return pou
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pou *PollOptionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pou.sqlSave, pou.mutation, pou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pou *PollOptionUpdate) SaveX(ctx context.Context) int {
	affected, err := pou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pou *PollOptionUpdate) Exec(ctx context.Context) error {
	_, err := pou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pou *PollOptionUpdate) ExecX(ctx context.Context) {
	if err := pou.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pou *PollOptionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(polloption.Table, polloption.Columns, sqlgraph.NewFieldSpec(polloption.FieldID, field.TypeInt))
	if ps := pou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pou.mutation.Name(); ok {
		_spec.SetField(polloption.FieldName, field.TypeString, value)
	}
	if value, ok := pou.mutation.VoteCount(); ok {
		_spec.SetField(polloption.FieldVoteCount, field.TypeInt, value)
	}
	if value, ok := pou.mutation.AddedVoteCount(); ok {
		_spec.AddField(polloption.FieldVoteCount, field.TypeInt, value)
	}
	if pou.mutation.UsersVotedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   polloption.UsersVotedTable,
			Columns: polloption.UsersVotedPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pou.mutation.RemovedUsersVotedIDs(); len(nodes) > 0 && !pou.mutation.UsersVotedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   polloption.UsersVotedTable,
			Columns: polloption.UsersVotedPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pou.mutation.UsersVotedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   polloption.UsersVotedTable,
			Columns: polloption.UsersVotedPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pou.mutation.PollCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   polloption.PollTable,
			Columns: []string{polloption.PollColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(poll.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pou.mutation.PollIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   polloption.PollTable,
			Columns: []string{polloption.PollColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(poll.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{polloption.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pou.mutation.done = true
	return n, nil
}

// PollOptionUpdateOne is the builder for updating a single PollOption entity.
type PollOptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PollOptionMutation
}

// SetName sets the "name" field.
func (pouo *PollOptionUpdateOne) SetName(s string) *PollOptionUpdateOne {
	pouo.mutation.SetName(s)
	return pouo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pouo *PollOptionUpdateOne) SetNillableName(s *string) *PollOptionUpdateOne {
	if s != nil {
		pouo.SetName(*s)
	}
	return pouo
}

// SetVoteCount sets the "vote_count" field.
func (pouo *PollOptionUpdateOne) SetVoteCount(i int) *PollOptionUpdateOne {
	pouo.mutation.ResetVoteCount()
	pouo.mutation.SetVoteCount(i)
	return pouo
}

// SetNillableVoteCount sets the "vote_count" field if the given value is not nil.
func (pouo *PollOptionUpdateOne) SetNillableVoteCount(i *int) *PollOptionUpdateOne {
	if i != nil {
		pouo.SetVoteCount(*i)
	}
	return pouo
}

// AddVoteCount adds i to the "vote_count" field.
func (pouo *PollOptionUpdateOne) AddVoteCount(i int) *PollOptionUpdateOne {
	pouo.mutation.AddVoteCount(i)
	return pouo
}

// AddUsersVotedIDs adds the "users_voted" edge to the User entity by IDs.
func (pouo *PollOptionUpdateOne) AddUsersVotedIDs(ids ...int) *PollOptionUpdateOne {
	pouo.mutation.AddUsersVotedIDs(ids...)
	return pouo
}

// AddUsersVoted adds the "users_voted" edges to the User entity.
func (pouo *PollOptionUpdateOne) AddUsersVoted(u ...*User) *PollOptionUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return pouo.AddUsersVotedIDs(ids...)
}

// SetPollID sets the "poll" edge to the Poll entity by ID.
func (pouo *PollOptionUpdateOne) SetPollID(id int) *PollOptionUpdateOne {
	pouo.mutation.SetPollID(id)
	return pouo
}

// SetNillablePollID sets the "poll" edge to the Poll entity by ID if the given value is not nil.
func (pouo *PollOptionUpdateOne) SetNillablePollID(id *int) *PollOptionUpdateOne {
	if id != nil {
		pouo = pouo.SetPollID(*id)
	}
	return pouo
}

// SetPoll sets the "poll" edge to the Poll entity.
func (pouo *PollOptionUpdateOne) SetPoll(p *Poll) *PollOptionUpdateOne {
	return pouo.SetPollID(p.ID)
}

// Mutation returns the PollOptionMutation object of the builder.
func (pouo *PollOptionUpdateOne) Mutation() *PollOptionMutation {
	return pouo.mutation
}

// ClearUsersVoted clears all "users_voted" edges to the User entity.
func (pouo *PollOptionUpdateOne) ClearUsersVoted() *PollOptionUpdateOne {
	pouo.mutation.ClearUsersVoted()
	return pouo
}

// RemoveUsersVotedIDs removes the "users_voted" edge to User entities by IDs.
func (pouo *PollOptionUpdateOne) RemoveUsersVotedIDs(ids ...int) *PollOptionUpdateOne {
	pouo.mutation.RemoveUsersVotedIDs(ids...)
	return pouo
}

// RemoveUsersVoted removes "users_voted" edges to User entities.
func (pouo *PollOptionUpdateOne) RemoveUsersVoted(u ...*User) *PollOptionUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return pouo.RemoveUsersVotedIDs(ids...)
}

// ClearPoll clears the "poll" edge to the Poll entity.
func (pouo *PollOptionUpdateOne) ClearPoll() *PollOptionUpdateOne {
	pouo.mutation.ClearPoll()
	return pouo
}

// Where appends a list predicates to the PollOptionUpdate builder.
func (pouo *PollOptionUpdateOne) Where(ps ...predicate.PollOption) *PollOptionUpdateOne {
	pouo.mutation.Where(ps...)
	return pouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pouo *PollOptionUpdateOne) Select(field string, fields ...string) *PollOptionUpdateOne {
	pouo.fields = append([]string{field}, fields...)
	return pouo
}

// Save executes the query and returns the updated PollOption entity.
func (pouo *PollOptionUpdateOne) Save(ctx context.Context) (*PollOption, error) {
	return withHooks(ctx, pouo.sqlSave, pouo.mutation, pouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pouo *PollOptionUpdateOne) SaveX(ctx context.Context) *PollOption {
	node, err := pouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pouo *PollOptionUpdateOne) Exec(ctx context.Context) error {
	_, err := pouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pouo *PollOptionUpdateOne) ExecX(ctx context.Context) {
	if err := pouo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pouo *PollOptionUpdateOne) sqlSave(ctx context.Context) (_node *PollOption, err error) {
	_spec := sqlgraph.NewUpdateSpec(polloption.Table, polloption.Columns, sqlgraph.NewFieldSpec(polloption.FieldID, field.TypeInt))
	id, ok := pouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PollOption.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, polloption.FieldID)
		for _, f := range fields {
			if !polloption.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != polloption.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pouo.mutation.Name(); ok {
		_spec.SetField(polloption.FieldName, field.TypeString, value)
	}
	if value, ok := pouo.mutation.VoteCount(); ok {
		_spec.SetField(polloption.FieldVoteCount, field.TypeInt, value)
	}
	if value, ok := pouo.mutation.AddedVoteCount(); ok {
		_spec.AddField(polloption.FieldVoteCount, field.TypeInt, value)
	}
	if pouo.mutation.UsersVotedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   polloption.UsersVotedTable,
			Columns: polloption.UsersVotedPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pouo.mutation.RemovedUsersVotedIDs(); len(nodes) > 0 && !pouo.mutation.UsersVotedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   polloption.UsersVotedTable,
			Columns: polloption.UsersVotedPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pouo.mutation.UsersVotedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   polloption.UsersVotedTable,
			Columns: polloption.UsersVotedPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pouo.mutation.PollCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   polloption.PollTable,
			Columns: []string{polloption.PollColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(poll.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pouo.mutation.PollIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   polloption.PollTable,
			Columns: []string{polloption.PollColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(poll.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PollOption{config: pouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{polloption.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	pouo.mutation.done = true
	return _node, nil
}
