// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PollsColumns holds the columns for the "polls" table.
	PollsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "user_created_polls", Type: field.TypeInt, Nullable: true},
	}
	// PollsTable holds the schema information for the "polls" table.
	PollsTable = &schema.Table{
		Name:       "polls",
		Columns:    PollsColumns,
		PrimaryKey: []*schema.Column{PollsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "polls_users_created_polls",
				Columns:    []*schema.Column{PollsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// PollOptionsColumns holds the columns for the "poll_options" table.
	PollOptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "vote_count", Type: field.TypeInt},
		{Name: "poll_poll_options", Type: field.TypeInt, Nullable: true},
	}
	// PollOptionsTable holds the schema information for the "poll_options" table.
	PollOptionsTable = &schema.Table{
		Name:       "poll_options",
		Columns:    PollOptionsColumns,
		PrimaryKey: []*schema.Column{PollOptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "poll_options_polls_poll_options",
				Columns:    []*schema.Column{PollOptionsColumns[3]},
				RefColumns: []*schema.Column{PollsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "first_name", Type: field.TypeString},
		{Name: "last_name", Type: field.TypeString},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// PollOptionUsersVotedColumns holds the columns for the "poll_option_users_voted" table.
	PollOptionUsersVotedColumns = []*schema.Column{
		{Name: "poll_option_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// PollOptionUsersVotedTable holds the schema information for the "poll_option_users_voted" table.
	PollOptionUsersVotedTable = &schema.Table{
		Name:       "poll_option_users_voted",
		Columns:    PollOptionUsersVotedColumns,
		PrimaryKey: []*schema.Column{PollOptionUsersVotedColumns[0], PollOptionUsersVotedColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "poll_option_users_voted_poll_option_id",
				Columns:    []*schema.Column{PollOptionUsersVotedColumns[0]},
				RefColumns: []*schema.Column{PollOptionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "poll_option_users_voted_user_id",
				Columns:    []*schema.Column{PollOptionUsersVotedColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PollsTable,
		PollOptionsTable,
		UsersTable,
		PollOptionUsersVotedTable,
	}
)

func init() {
	PollsTable.ForeignKeys[0].RefTable = UsersTable
	PollOptionsTable.ForeignKeys[0].RefTable = PollsTable
	PollOptionUsersVotedTable.ForeignKeys[0].RefTable = PollOptionsTable
	PollOptionUsersVotedTable.ForeignKeys[1].RefTable = UsersTable
}
